spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123

jwt:
  header: jwtHeader
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl #jwt 的加密字符串
  expiration: 36000000
  route:
    login: /auth/login     #登录地址
    refresh: /auth/refresh #刷新Token的地址
    register: /auth/register   # 注册用户，这个接口后续需要改变
    info: /auth/info # 获取当前登录用户的信息   